import Foundation

/// Installs / removes an opencode plugin that drives Conterm's per-pane
/// status pill, mirroring the Claude Code integration.
///
/// opencode uses a JS/TS plugin system (not a JSON hooks array), so we
/// drop a single dedicated file at ~/.config/opencode/plugin/ — install
/// = write it, uninstall = delete it. Because it's our own file we
/// never touch the user's config or other plugins (inherently safe; no
/// merge/backup needed). The plugin writes the same private OSC that
/// the Claude hooks do — `OSC 9 ; conterm-agent:opencode:<state> BEL`
/// — straight to the controlling tty, which libghostty hands Conterm.
///
/// opencode plugin lifecycle events used:
///   session.created → start  → "opencode is Ready."
///   session.updated / message.updated → prompt → "opencode is thinking…"
///   session.idle    → idle   → back to "opencode is Ready."
///   session.deleted → end    → pill disappears
@MainActor
enum OpenCodeIntegration {
    private static var dir: String {
        "\(NSHomeDirectory())/.config/opencode/plugin"
    }
    private static var path: String { "\(dir)/conterm-agent.js" }

    static var isInstalled: Bool {
        FileManager.default.fileExists(atPath: path)
    }

    private static let plugin = #"""
    // Auto-generated by Conterm — drives Conterm's agent status pill.
    // Safe to delete (or toggle off "opencode integration" in Conterm).
    import { writeFileSync } from "node:fs";

    let last = "";
    function raw(state) {
      try {
        // Raw OSC 9 to the controlling terminal; Conterm only reacts
        // to the `conterm-agent:` prefix so this never spams anything.
        writeFileSync("/dev/tty", "\x1b]9;conterm-agent:opencode:" + state + "\x07");
      } catch (e) { /* not a tty / no permission — ignore */ }
    }
    function send(state) {
      // Dedupe: message.updated fires many times a second while
      // opencode streams; only emit on an actual state change.
      if (state === last) return;
      last = state;
      raw(state);
    }

    // The pill must vanish when opencode quits. The plugin dies WITH
    // opencode, so no `session.deleted` ever arrives — the only
    // reliable signal is a synchronous write from a process-exit
    // handler (writeFileSync works during exit).
    let ended = false;
    function end() { if (!ended) { ended = true; raw("end"); } }
    process.on("exit", end);
    process.on("SIGINT", () => { end(); process.exit(0); });
    process.on("SIGTERM", () => { end(); process.exit(0); });

    export const contermAgent = async () => {
      // Emit "start" the instant opencode loads the plugin (startup),
      // so the pill appears immediately — `session.created` is lazy
      // and was why nothing showed when you launched opencode.
      raw("start"); last = "start";
      return {
        event: async ({ event }) => {
          switch (event && event.type) {
            // "working" only from an assistant message streaming —
            // `session.updated` also fires at idle, which made the
            // pill say "ready" while it was actually thinking.
            case "message.updated":  send("prompt"); break;
            case "session.idle":     send("idle"); break;
            case "session.created":  send("start"); break;
            case "session.deleted":  end(); break;
          }
        },
      };
    };
    """#

    static func install() {
        try? FileManager.default.createDirectory(
            atPath: dir, withIntermediateDirectories: true)
        try? plugin.write(toFile: path, atomically: true, encoding: .utf8)
    }

    static func uninstall() {
        try? FileManager.default.removeItem(atPath: path)
    }

    /// Rewrite the plugin to the current version on launch if it's
    /// installed, so app updates ship fixes without a manual re-toggle.
    static func refreshIfInstalled() {
        if isInstalled { install() }
    }
}
