#!/usr/bin/env bash
# Builds Conterm.app from a SwiftPM executable. We can't use xcodebuild
# (Command Line Tools only), so we hand-assemble the .app bundle.
set -euo pipefail

cd "$(dirname "$0")/.."

CONFIG="${CONFIG:-release}"
APP="Conterm.app"

bash scripts/setup.sh

echo "==> swift build -c $CONFIG (arm64)"
swift build -c "$CONFIG" --arch arm64

BIN_PATH=$(swift build -c "$CONFIG" --arch arm64 --show-bin-path)
EXE="$BIN_PATH/Conterm"

if [[ ! -x "$EXE" ]]; then
    echo "Build did not produce $EXE" >&2
    exit 1
fi

echo "==> assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$EXE" "$APP/Contents/MacOS/Conterm"
cp Resources/Info.plist "$APP/Contents/Info.plist"
cp Resources/PrivacyInfo.xcprivacy "$APP/Contents/Resources/PrivacyInfo.xcprivacy"
echo -n "APPL????" > "$APP/Contents/PkgInfo"

# Pack ICONS_FINAL/*.png into AppIcon.icns AS-IS (no rendering, no
# masking). iconutil just bundles the raw PNGs into the .icns
# container — every pixel of every size is byte-for-byte what you
# put in ICONS_FINAL/.
if [[ -d ICONS_FINAL ]] && command -v iconutil >/dev/null 2>&1; then
    ICONSET="$(mktemp -d)/AppIcon.iconset"
    mkdir -p "$ICONSET"
    # iconutil expects these exact filenames:
    #   icon_16x16.png   icon_16x16@2x.png   (16, 32)
    #   icon_32x32.png   icon_32x32@2x.png   (32, 64)
    #   icon_128x128.png icon_128x128@2x.png (128, 256)
    #   icon_256x256.png icon_256x256@2x.png (256, 512)
    #   icon_512x512.png icon_512x512@2x.png (512, 1024)
    cp ICONS_FINAL/16.png   "$ICONSET/icon_16x16.png"
    cp ICONS_FINAL/32.png   "$ICONSET/icon_16x16@2x.png"
    cp ICONS_FINAL/32.png   "$ICONSET/icon_32x32.png"
    cp ICONS_FINAL/64.png   "$ICONSET/icon_32x32@2x.png"
    cp ICONS_FINAL/128.png  "$ICONSET/icon_128x128.png"
    cp ICONS_FINAL/256.png  "$ICONSET/icon_128x128@2x.png"
    cp ICONS_FINAL/256.png  "$ICONSET/icon_256x256.png"
    cp ICONS_FINAL/512.png  "$ICONSET/icon_256x256@2x.png"
    cp ICONS_FINAL/512.png  "$ICONSET/icon_512x512.png"
    cp ICONS_FINAL/1024.png "$ICONSET/icon_512x512@2x.png"
    iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
    # Also drop the raw PNG next to the icns as a fallback some
    # macOS surfaces look at first (and so the Finder Get-Info
    # icon-well shows the un-masked design directly).
    cp ICONS_FINAL/1024.png "$APP/Contents/Resources/AppIcon.png"
    rm -rf "$(dirname "$ICONSET")"
    echo "OK: bundled icon from ICONS_FINAL (raw, no rendering)"
elif [[ -f Resources/AppIcon.icns ]]; then
    cp Resources/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
    echo "OK: bundled icon from Resources/AppIcon.icns (ICONS_FINAL not found)"
fi

# Bundle Ghostty's GENUINE default config (generated by setup.sh from
# `ghostty +show-config --default`). This is the base config Conterm
# loads — a real, machine-independent Ghostty default, not a personal
# config. Also keep the small legacy default.conf around for reference.
cp Resources/ghostty-default.conf "$APP/Contents/Resources/ghostty-default.conf"
[[ -f Resources/default.conf ]] && cp Resources/default.conf "$APP/Contents/Resources/default.conf"

# Bundle libghostty's shell-integration / themes directory (mirrored
# from Ghostty.app by scripts/setup.sh). At runtime our app sets
# GHOSTTY_RESOURCES_DIR pointing at this path so libghostty can
# inject ZDOTDIR/ENV for shell-integration.
if [[ -d Resources/ghostty ]]; then
    cp -R Resources/ghostty "$APP/Contents/Resources/ghostty"
    # Conterm's own zsh hooks ride the same integration entry point.
    # Appended into the BUILT bundle only, so setup.sh can regenerate
    # Resources/ghostty from Ghostty.app without losing them.
    ZSH_INTEGRATION="$APP/Contents/Resources/ghostty/shell-integration/zsh/ghostty-integration"
    if [[ -f "$ZSH_INTEGRATION" && -f Resources/conterm-integration.zsh ]]; then
        cat Resources/conterm-integration.zsh >> "$ZSH_INTEGRATION"
        echo "OK: appended conterm zsh hooks to shell integration"
    fi
    echo "OK: bundled Resources/ghostty ($(du -sh "$APP/Contents/Resources/ghostty" | cut -f1))"
fi

# Bundle the compiled `xterm-ghostty` terminfo so spawned shells can
# resolve the TERM we advertise. Without this, ncurses falls back to
# xterm-256color, which doesn't understand Kitty keyboard protocol
# sequences libghostty emits — symptoms: zsh plugins misfire on key
# presses, modified keys leak escape sequences, etc.
if [[ -d Resources/terminfo ]]; then
    cp -R Resources/terminfo "$APP/Contents/Resources/terminfo"
    echo "OK: bundled Resources/terminfo ($(du -sh "$APP/Contents/Resources/terminfo" | cut -f1))"
fi

# Bundle app resources FLAT into Contents/Resources/ so they load via
# Bundle.main with a plain path lookup. We deliberately do NOT rely on
# SwiftPM's Conterm_Conterm.bundle + Bundle.module at runtime: that
# accessor fatalError()s if it can't resolve the nested bundle, which
# crashed the app on AirDropped / quarantined / translocated copies
# (the nested bundle isn't reliably resolvable there). A flat copy +
# nil-safe Bundle.main lookup degrades gracefully instead of crashing.
for res in Sources/Conterm/Resources/*; do
    [[ -e "$res" ]] || continue
    cp -R "$res" "$APP/Contents/Resources/"
done
if [[ -f "$APP/Contents/Resources/cursor-mark.png" ]]; then
    echo "OK: bundled flat app resources (cursor-mark.png, …)"
fi

echo "==> ad-hoc codesign"
# Strip extended attrs (resource forks etc.) so codesign doesn't
# choke. Otherwise we get "resource fork, Finder information, or
# similar detritus not allowed" on subsequent re-signs.
xattr -cr "$APP"
# PROFILE=1: grant the task port so Instruments / xctrace can attach
# and sample (hardened runtime denies it otherwise). Never ship a
# profile build — debugger access to the process is a security hole.
ENTITLEMENTS=Resources/Conterm.entitlements
if [[ "${PROFILE:-0}" == "1" ]]; then
    ENTITLEMENTS=$(mktemp -t conterm-profile-entitlements)
    plutil -convert xml1 -o "$ENTITLEMENTS" Resources/Conterm.entitlements
    plutil -insert 'com\.apple\.security\.get-task-allow' -bool true "$ENTITLEMENTS"
    echo "PROFILE build: get-task-allow granted (Instruments can attach)"
fi
# Explicit designated requirement: TCC matches apps by their designated
# requirement, and an ad-hoc signature's default DR is the per-build
# cdhash, which would re-prompt for folder access on every rebuild.
# Pinning the DR to the bundle identifier keeps approvals across builds.
DR='designated => identifier "app.conterm.Conterm"'
if codesign --force --sign - \
    --identifier app.conterm.Conterm \
    --requirements "=$DR" \
    --entitlements "$ENTITLEMENTS" \
    --options runtime \
    "$APP"; then
    echo "OK: signed with entitlements + hardened runtime"
else
    echo "WARN: entitlements/hardened-runtime signing failed — falling back to a" >&2
    echo "      bare ad-hoc sign (NO entitlements, NO hardened runtime)." >&2
    codesign --force --sign - "$APP"
fi

echo "OK: ./$APP"
echo "Run with: open ./$APP   (or ./$APP/Contents/MacOS/Conterm for console logs)"
